server:
  port: 8207
spring:
  application:
    name: service-orders
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_order?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: password
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  redis:
    database: 0
    host: 192.168.56.101
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    username: guest
    password: guest
