# 服务端口
server:
  port: 8201
# 服务名
spring:
  application:
    name: service-hosp
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.101:3306/yygh_hosp?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: password
  data:
    mongodb:
      uri: mongodb://192.168.56.101:27017/yygh
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    username: guest
    password: guest

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl