version: "3"
services:
  mysql:
    image: mysql:8
    container_name: yygh-mysql8
    restart: always
    ports:
      - 3306:3306
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Shanghai

  mongodb:
    image: mongo:4.4.8
    container_name: yygh-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db

  redis:
    image: redis
    container_name: yygh-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data

  nginx:
    image: nginx:latest
    container_name: yygh-nginx
    restart: always
    ports:
      - 80:80
      - 9001:9001
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/html:/etc/nginx/html

  nacos:
    image: nacos/nacos-server:1.1.4
    container_name: yygh-nacos
    restart: always
    ports:
      - 8848:8848
    volumes:
      - ./nacos/logs:/home/nacos/logs
      - ./nacos/conf:/home/nacos/conf
      - ./nacos/data:/home/nacos/data
    environment:
      - PREFER_HOST_MODE=ip
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=2222
      - NACOS_AUTH_IDENTITY_VALUE=2xxx
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
