server:
  port: 8208
spring:
  application:
    name: service-task
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848
  profiles:
    active: dev
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    username: guest
    password: guest
