server:
  port: 8204
spring:
  application:
    name: service-msm
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: 192.168.56.101
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    username: guest
    password: guest
