server:
  port: 8207
spring:
  application:
    name: service-orders
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.101:3306/yygh_order?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: password
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  redis:
    database: 0
    host: 192.168.56.101
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    username: guest
    password: guest

# 关联的公众号appid
weixin:
  pay:
    # 关联的公众号appid
    appid: wx74862e0dfcf69954
    # 商户号
    partner: 1558950191
    # 商户key
    partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
